class URLs:
    REGISTER = "/api/v1/auth/register"
    LOGIN = "/api/v1/auth/login"
    TOKENS = "/api/v1/tokens"
    WORKSPACES = "/api/v1/workspaces"
    WORKSPACES_DELETE = "/api/v1/workspaces/{}"
    WORKSPACES_SETTINGS = "/api/v1/workspaces/{}/settings"
    USERS_ME = "/api/v1/users/me"
    FCS_PARAMETERS = "/api/v1/fcs/parameters"
    FCS_PARAMETERS_WITH_ID = "/api/v1/fcs/parameters?file_id={}"
    FCS_EVENTS = "/api/v1/fcs/events"
